version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: database-dustmeasuringdashboard.cheosu8kisha.ap-southeast-2.rds.amazonaws.com
      DB_PORT: 1433
      DB_USER: admin
      DB_PASSWORD: Strongpass1234
      DB_NAME: dashboardDB
      DB_DIALECT: mssql
      PORT: 5000
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Strongpass1234"
      MSSQL_PID: "Express"
