name: CI/CD - Deploy Backend to AWS EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Deploy to EC2 via SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 52.64.110.28
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          # Navigate to the project directory or clone the repository if needed
          cd /home/ubuntu/DustMeasuringDashboard || git clone https://github.com/JaySorawit/DustMeasuringDashboard.git /home/ubuntu/DustMeasuringDashboard && cd /home/ubuntu/DustMeasuringDashboard
          git pull origin main

          # Build the Docker image
          cd server
          docker build -t dustmeasuringdashboard-backend .

          # Stop and remove the existing container if it exists
          docker ps -q --filter "name=dustmeasuringdashboard-backend" | grep -q . && docker stop dustmeasuringdashboard-backend && docker rm dustmeasuringdashboard-backend || true

          # Run the new container
          docker run -d -p 5000:5000 \
              -e DB_HOST=database-dustmeasuringdashboard.cheosu8kisha.ap-southeast-2.rds.amazonaws.com \
              -e DB_PORT=1433 \
              -e DB_USER=admin \
              -e DB_PASSWORD=Strongpass1234 \
              -e DB_NAME=dashboardDB \
              -e DB_DIALECT=mssql \
              -e PORT=5000 \
              --name dustmeasuringdashboard-backend \
              dustmeasuringdashboard-backend
